#!/bin/bash
set -x
LFILE=/tmp/firefox.log
FXLANG=${1:-es-ES}
cd /tmp
wget "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=${FXLANG}" -o $LFILE
VERSION=$(grep releases $LFILE|awk -F/ '{ print $7 }'|head -n 1)

FIREALL=$(grep index $LFILE|head -n 1|awk '{ print $3 }')
OFILE=/tmp/${FIREALL:1:-1}

echo "#!/bin/bash
MOZILLA_HOME=/usr/local/firefox
\$MOZILLA_HOME/firefox \$@ &
">/usr/local/bin/firefox
chmod a+x /usr/local/bin/firefox

if (( $(ps -ef|grep /usr/local/firefox-|head -n2|wc -l) == 2 ));then
    echo "Corriendo firefox"
    OLDVERSION=$(ps -ef|grep /usr/local/firefox-|head -n1|awk '{ print $8 }')
    for F in /usr/local/firefox-*;do
	if [[ $OLDVERSION != $F/firefox-bin ]];then
		rm -rf $F
	fi
    done

else
    echo "Firefox no está corriendo"
    for F in /usr/local/firefox-*;do
	if [[ /usr/local/firefox-$VERSION != $F ]];then
	    rm -rf $F
	fi
    done
fi

if [ -d /usr/local/firefox-$VERSION ];then
    echo "No se actualiza"
else
    if [ -f /usr/local/firefox ];then
	rm /usr/local/firefox 2>/dev/null
    fi

    if [ -f /usr/local/firefox-${VERSION}/firefox-bin ];then
	if [[ -z $(ps -ef|grep firefox-${VERSION}) ]];then
	    echo "rm -rf /usr/local/firefox-$VERSION"
	else
	    echo "Se está ejecutando"
	fi
    fi



    FILETYPE=$(file -b "$OFILE")
    rm /usr/local/firefox
    echo "Uncompressiong firefox $VERSION..."

    # Uncompress according FILETYPE
    if [[ "$FILETYPE" == *"gzip compressed data"* ]]; then
	tar -xzf "$OFILE" -C /usr/local
    elif [[ "$FILETYPE" == *"bzip2 compressed data"* ]]; then
	tar -xjf "$OFILE" -C /usr/local
    elif [[ "$FILETYPE" == *"XZ compressed data"* ]]; then
	tar -xJf "$OFILE" -C /usr/local
    elif [[ "$FILETYPE" == *"POSIX tar archive"* ]]; then
	tar -xf "$OFILE" -C /usr/local
    else
	exit 1
    fi

    mv /usr/local/firefox/ /usr/local/firefox-$VERSION
    ln -s firefox-$VERSION /usr/local/firefox

fi

rm $OFILE 2>/dev/null
